In [8]:
import numpy as np
import time

In [9]:
a = np.array([1,2,3,4])

In [10]:
print(a)

[1 2 3 4]


In [11]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorised version: " + str(1000*(toc-tic))+"ms")

249926.12934426678
Vectorised version: 2.6950836181640625ms


In [12]:
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("Loop version: " + str(1000*(toc-tic))+"ms")

249926.12934426728
Loop version: 298.9611625671387ms


In [13]:
x = np.array([5,7,3])
y = np.array([90,50,0])
x*y

array([450, 350,   0])

In [15]:
v = np.array([12,24,36])
w = np.array([45,55])

np.reshape(v,(3,1)) * w

array([[ 540,  660],
       [1080, 1320],
       [1620, 1980]])

In [17]:
A = np.array([[56,1,4.4,68],
             [1.2,104,52,8],
             [1.8, 135, 99, 0.9]])

In [18]:
A

array([[ 56. ,   1. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [31]:
A.sum(axis=0)
print(A.sum(axis=0).shape)

(4,)


In [34]:
A/A.sum(axis=0).reshape(1,4) * 100

array([[94.91525424,  0.41666667,  2.83140283, 88.42652796],
       [ 2.03389831, 43.33333333, 33.46203346, 10.40312094],
       [ 3.05084746, 56.25      , 63.70656371,  1.17035111]])

Always give your arrays shape, and stay away from rank 1 arrays!

In [46]:
# Rank 1 Arrays
p = np.random.randn(5)
print(p.shape)
print(p)
print(p.T)

p_rs = np.reshape(p,(5,1))
print(p_rs.shape)

print("===========================================")

# Giving Arrays a shape
q = np.random.randn(5,1)
print(q.shape)
print(q)
print(q.T)
print(q.T.shape)


(5,)
[ 1.82612614  1.45358113 -0.30191689  1.13126576 -0.78790255]
[ 1.82612614  1.45358113 -0.30191689  1.13126576 -0.78790255]
(5, 1)
(5, 1)
[[-1.07634936]
 [ 0.6854941 ]
 [ 0.24778007]
 [-1.46614113]
 [ 1.8389635 ]]
[[-1.07634936  0.6854941   0.24778007 -1.46614113  1.8389635 ]]
(1, 5)


In [44]:
assert(q.T.shape == (1,5))
assert(q.T.shape == (1,1))

AssertionError: 

In [48]:
from math import log


log(1-0.5)

-0.6931471805599453

In [56]:
np.random.randn(4,3) * np.random.randn(3,2)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [55]:
m = np.array([[2,1],[1,3]])

np.dot(m,m)
m

array([[2, 1],
       [1, 3]])